@echo off
echo Activating virtual environment...
call venv\Scripts\activate

echo Installing dependencies...
pip install -r requirements.txt

echo Starting Backend Server...
python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
